databases:
  - name: postgres
    ipAllowList: []
    
 services:
    - type: web
      name: rails
      env: ruby
      buildCommand: "./bin/render-build.sh"
      startCommand: bundle exec rails s
      envVars:
        - key: RAULS_MASTER_KEY
          sync: false
        - keu: DATABASE_URL
          fromDatabase:
            name: postgres
            property: connectionString
    - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
