databases:
  - name: cash_in_out_development
    databaseName: geekelo
    user: geekelo

services:
  - type: web
    name: geekelo
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: geekelo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false